# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67b694cfec84d64bb2bca4769e63fa5f4e8b36a53bc3c4b1cb5511e740b1e3d89a530c192d2597cdff463147e6723cc6e7f034a998296f7300df7c127a77506b

test:
  secret_key_base: 63110c4426beac73e06a64612702605104ea62307680a3a332e7413fa6eb8ed4660d22d4b775899cf5df712394d83aebcbc30450a423c27329b47dcbc19d1673

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
